reload('user.options')
reload('user.plugins')
reload('user.nvim-ts-autotag')
reload('user.nvim-surround')
reload('user.lsp')
reload('user.colorizer')
reload('user.noice')
-- reload('user.statusline')
-- reload('user.nvim-lint')
-- reload('user.confirm')
-- reload('user.toggleterm')
require("lvim.lsp.manager").setup("angularls")
